name: Build & Deploy to EC2

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '24'

      - name: Build frontend
        working-directory: frontend/public-site
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
          npm run build -- --configuration production

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '9.0.x'

      - name: Publish backend
        working-directory: src/PersonalSite.Web
        run: dotnet publish -c Release -o publish

      - name: Archive artifacts
        run: |
          ls -la frontend/public-site/dist || true
          ls -la src/PersonalSite.Web/publish || true

          tar czf frontend.tar.gz -C frontend/public-site/dist/public-site .
          tar czf backend.tar.gz -C src/PersonalSite.Web/publish .

          mkdir -p deploy-package
          mv frontend.tar.gz backend.tar.gz deploy-scripts deploy-package/
          ls -la deploy-package

      - name: show workspace before deploy
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          pwd
          ls -la

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_IP }}
          REMOTE_USER: ec2-user
          SOURCE: deploy-package/
          TARGET: "/home/ec2-user/deploy/"
          SCRIPT_BEFORE: |
            echo "remote before rsync:"
            ls -la /home/ec2-user/deploy || true

      - name: Run deploy script
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ec2-user/deploy
            echo "PWD: $(pwd)"
            ls -la
            if [ -f deploy-scripts/deploy.sh ]; then
              echo "Found script, executing with full path"
              sudo bash /home/ec2-user/deploy/deploy-scripts/deploy.sh
            else
              echo "ERROR: deploy.sh not found"
              exit 1
            fi
